name: pull_workflow
on:
  # pull_request_review:
  #   types: [submitted]
  pull_request_target:
    types: [synchronize,opened,closed,review_requested,review_submitted]   

permissions:
  contents: read
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./\.github/workflows/scripts/pull_workflow.js')
            script({github, context})
